// Mocked-DOM test for the Marine Protected Area warning UI (Section 14o) -
// same technique as test_boundary_warning_ui.js (concatenate the real
// config.js/map.js/voice.js/chat.js as ONE unit via node's vm module,
// exact production <script> order, minimal hand-rolled Leaflet + DOM mock).
//
// Route data comes from the SAME route_fixtures.json used by
// test_boundary_warning_ui.js, regenerated by
// tests/generate_route_fixtures.py to include a genuine "mpa_warning"
// scenario (Mandapam -> a real point inside the actual fetched Gulf of
// Mannar Marine Biosphere Reserve polygon - real WDPA/Protected Planet
// data as of Section 14u, no longer the earlier Wikipedia-sourced
// placeholder rectangle). This test specifically
// confirms: (1) the MPA warning renders with its OWN distinct visual
// treatment (teal, not the boundary warning's magenta), (2) it never
// fires on scenarios that don't have it, and (3) a route flagged for
// BOTH boundary_warning and mpa_warning would show both overlays
// simultaneously (checked structurally, even though no single fixture
// scenario happens to trigger both at once).
//
// Usage:
//   node frontend/tests/test_mpa_warning_ui.js

const fs = require('fs');
const path = require('path');
const vm = require('vm');

let passed = 0;
let failed = 0;
function check(label, condition, detail) {
  if (condition) {
    console.log(`  PASS: ${label}`);
    passed++;
  } else {
    console.log(`  FAIL: ${label}${detail ? ' - ' + detail : ''}`);
    failed++;
  }
}

// ---------- Minimal Leaflet mock (same as test_boundary_warning_ui.js) ----------
const createdLayers = [];

function mockLayer(type, options) {
  const layer = { type, options, popupContent: null };
  layer.addTo = () => { createdLayers.push(layer); return layer; };
  layer.bindPopup = (html) => { layer.popupContent = html; return layer; };
  layer.on = () => layer;
  return layer;
}

const L = {
  latLngBounds: (pts) => ({ _points: pts }),
  map: () => ({ setView() { return this; }, removeLayer() {}, fitBounds() {}, on() { return this; } }),
  tileLayer: () => ({ addTo() { return this; } }),
  control: () => { const c = {}; c.addTo = () => c; return c; },
  DomUtil: { create: (tag) => makeElement(tag) },
  circleMarker: (latlng, opts) => mockLayer('circleMarker', { latlng, ...opts }),
  marker: (latlng, opts) => mockLayer('marker', { latlng, ...opts }),
  polyline: (latlngs, opts) => mockLayer('polyline', { latlngs, ...opts }),
};

// ---------- Minimal DOM mock ----------
function makeElement(tag) {
  return {
    tagName: tag,
    className: '',
    innerHTML: '',
    style: {},
    textContent: '',
    children: [],
    appendChild(child) { this.children.push(child); return child; },
    querySelectorAll: () => [],
    addEventListener() {},
  };
}

const messagesEl = makeElement('div');
const document_ = {
  getElementById: (id) => (id === 'messages' ? messagesEl : makeElement('div')),
  createElement: (tag) => makeElement(tag),
  createTextNode: (text) => ({ nodeType: 3, textContent: text }),
  querySelectorAll: () => [],
};

const sandbox = {
  console,
  document: document_,
  L,
  fetch: () => Promise.reject(new Error('network disabled in this offline UI test')),
};
sandbox.window = sandbox;
vm.createContext(sandbox);

const jsDir = path.join(__dirname, '..', 'js');
const bundle = ['config.js', 'map.js', 'voice.js', 'chat.js']
  .map((f) => fs.readFileSync(path.join(jsDir, f), 'utf8'))
  .join('\n;\n');
vm.runInContext(bundle, sandbox, { filename: 'frontend-bundle.js' });

const fixtures = JSON.parse(fs.readFileSync(path.join(__dirname, 'route_fixtures.json'), 'utf8'));

function resetCapture() {
  createdLayers.length = 0;
  messagesEl.children.length = 0;
}

function runScenario(label, routeField, expectMpaWarning) {
  console.log('='.repeat(70));
  console.log(label);
  resetCapture();

  sandbox.renderRoute(routeField);
  sandbox.renderRouteInfoPanel(routeField);

  const mpaOverlays = createdLayers.filter((l) => l.type === 'polyline' && l.options.className === 'mpa-warning-overlay');
  const boundaryOverlays = createdLayers.filter((l) => l.type === 'polyline' && l.options.className === 'boundary-warning-overlay');
  const basePolylines = createdLayers.filter((l) => l.type === 'polyline' && !['mpa-warning-overlay', 'boundary-warning-overlay'].includes(l.options.className));
  const mpaWarnedRoutes = routeField.candidate_routes.filter((r) => r.mpa_warning === true);
  const boundaryWarnedRoutes = routeField.candidate_routes.filter((r) => r.boundary_warning === true);

  console.log(`  candidate routes: ${routeField.candidate_routes.length}, mpa_warning=true on: ${mpaWarnedRoutes.length}, boundary_warning=true on: ${boundaryWarnedRoutes.length}`);
  console.log(`  base polylines: ${basePolylines.length}, teal MPA overlays: ${mpaOverlays.length}, magenta boundary overlays: ${boundaryOverlays.length}`);

  check(
    'one teal .mpa-warning-overlay polyline per mpa_warning=true route',
    mpaOverlays.length === mpaWarnedRoutes.length,
    `expected ${mpaWarnedRoutes.length}, got ${mpaOverlays.length}`
  );

  if (mpaOverlays.length > 0) {
    check('MPA overlay color is teal (#00bfa5), NOT the boundary warning magenta', mpaOverlays.every((o) => o.options.color === '#00bfa5'));
    check('MPA overlay color is distinct from EEZ boundary overlay color', mpaOverlays.every((o) => o.options.color !== '#d500f9'));
    check('MPA overlay uses a dashed pattern (visually distinct stripe)', mpaOverlays.every((o) => typeof o.options.dashArray === 'string'));
  }

  // Regression check: the boundary-warning overlay/logic must be totally
  // unaffected by adding the MPA overlay code alongside it.
  check(
    'EEZ boundary overlay count unaffected by MPA changes',
    boundaryOverlays.length === boundaryWarnedRoutes.length,
    `expected ${boundaryWarnedRoutes.length}, got ${boundaryOverlays.length}`
  );

  const popupsWithMpaWarning = basePolylines.filter((p) => p.popupContent && p.popupContent.includes('MARINE PROTECTED AREA WARNING'));
  check(
    'route popup text includes the MPA warning + distance for every mpa_warning route',
    popupsWithMpaWarning.length === mpaWarnedRoutes.length,
    `expected ${mpaWarnedRoutes.length}, got ${popupsWithMpaWarning.length}`
  );
  if (mpaWarnedRoutes.length > 0) {
    const expectedKm = String(mpaWarnedRoutes[0].mpa_distance_km);
    check(
      `popup includes the actual MPA distance value (${expectedKm} km)`,
      popupsWithMpaWarning.some((p) => p.popupContent.includes(expectedKm))
    );
    check(
      'popup MPA warning text is distinct wording from the boundary warning text',
      popupsWithMpaWarning.every((p) => !p.popupContent.includes('MARITIME BOUNDARY WARNING') || boundaryWarnedRoutes.length > 0)
    );
  }

  const infoCard = messagesEl.children[messagesEl.children.length - 1];
  const recommended = routeField.candidate_routes.find((r) => r.is_recommended);
  const mpaBannerExpected = !!(recommended && recommended.mpa_warning === true);
  check(
    'route info panel shows the MPA banner iff the RECOMMENDED route has mpa_warning=true',
    infoCard.innerHTML.includes('route-mpa-banner') === mpaBannerExpected
  );
  if (mpaBannerExpected) {
    check(
      `MPA banner mentions the recommended route's own distance (${recommended.mpa_distance_km} km)`,
      infoCard.innerHTML.includes(String(recommended.mpa_distance_km))
    );
    check('MPA banner text is distinct from the boundary banner (mentions "protected"/"conservation")',
      infoCard.innerHTML.toLowerCase().includes('protected'));
  }

  check(
    `overall: this scenario ${expectMpaWarning ? 'DOES' : 'does NOT'} visually flag an MPA warning, as expected`,
    (mpaOverlays.length > 0) === expectMpaWarning
  );
  console.log();
}

runScenario(
  'SCENARIO 1: Mandapam -> Gulf of Mannar test area (real backend fixture w/ test MPA polygon, expect MPA warning)',
  fixtures.mpa_warning,
  true
);

runScenario(
  "SCENARIO 2: Kochi -> Kochi's nearest_pfz (expect NO MPA warning, NO boundary warning)",
  fixtures.no_warning,
  false
);

runScenario(
  'SCENARIO 3: Rameswaram -> Palk Strait boundary point (expect boundary warning but NOT MPA warning - different water bodies)',
  fixtures.boundary_warning,
  false
);

console.log('='.repeat(70));
console.log(`RESULTS: ${passed} passed, ${failed} failed`);
if (failed === 0) {
  console.log('All MPA-warning UI checks pass.');
} else {
  console.log('Some checks failed - review the FAIL lines above.');
  process.exitCode = 1;
}
